name: A workflow for Group Project
on: push

jobs:
  build:
    name: Group Project
    runs-on: ubuntu-22.04

    services:
      #begin MySql database container
      mysql:
        image: mysql:8.0
        ports: [ '3306:3306' ]

        env: #env variables to configure MySql
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: world
          MYSQL_USER: user
          MYSQL_PASSWORD: pass

        options: >-
          --health-cmd="mysqladmin ping -proot || exit 1"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=60
          

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Wait for MySql and import data
        run: |
          for i in {1..60}; do
            if mysql -h 127.0.0.1 -u root -proot -e "SELECT 1" &>/dev/null; then
              echo "MySQL is ready"; break
            fi
            sleep 2
          done
          
          mysql -h 127.0.0.1 -u root -proot world < data/world.sql

      - name: Package with Maven
        run: mvn -B -DskipTests package

      - name: Build Docker Image
        run: docker build -t devopsimage .

      - name: Run application
        run: |
          docker run --rm \
            --network host \
            -e DB_HOST=127.0.0.1 \
            -e DB_PORT=3306 \
            -e DB_NAME=world \
            -e DB_USER=user \
            -e DB_PASS=pass \
            devopsimage
      - name: Unit Tests
        run: mvn -Dtest=com.napier.sem.DatabaseManagerTest, com.napier.sem.ReportServiceTest test